FROM resin/raspberry-pi-alpine-python:3.7-slim

RUN apk add --update --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ \
        build-base

COPY boat.py requirments.txt /srv/

WORKDIR /srv

RUN pip install -r requirments.txt

CMD ./boat.py
EXPOSE 8000
